# Generated by Django 5.2.12 on 2026-03-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_summary_summary_summary_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
