# Generated by Django 5.2.12 on 2026-03-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='summary',
        ),
        migrations.AddField(
            model_name='summary',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='summary',
            name='full_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='insights',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='summary',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='reading_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
