# Generated by Django 5.2.12 on 2026-03-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_summary_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='wiki_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
